blank_issues_enabled: false
contact_links:
  - name: Questions and discussions
    url: https://github.com/sisyphos-ui/sisyphos-ui/discussions
    about: Open a discussion for questions, ideas, and general feedback.
