name: Chromatic

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  chromatic:
    runs-on: ubuntu-latest
    if: ${{ secrets.CHROMATIC_PROJECT_TOKEN != '' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build:storybook
          onlyChanged: true
          exitZeroOnChanges: true
